<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260608164511 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE device (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, serial_number VARCHAR(255) NOT NULL, model VARCHAR(255) NOT NULL, customer_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE technician (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, login_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F244E948E7927C74 ON technician (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F244E9485CB2E05D ON technician (login_id)');
        $this->addSql('CREATE TABLE ticket (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, priority VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, assigned_technician_id INT DEFAULT NULL, device_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_97A0ADA35CF77DD3 ON ticket (assigned_technician_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA394A4C7D4 ON ticket (device_id)');
        $this->addSql('CREATE TABLE ticket_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, old_status VARCHAR(255) DEFAULT NULL, new_status VARCHAR(255) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ticket_id INT NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B762919700047D2 ON ticket_history (ticket_id)');
        $this->addSql('CREATE INDEX IDX_2B762919B03A8386 ON ticket_history (created_by_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE technician ADD CONSTRAINT FK_F244E9485CB2E05D FOREIGN KEY (login_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA35CF77DD3 FOREIGN KEY (assigned_technician_id) REFERENCES technician (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA394A4C7D4 FOREIGN KEY (device_id) REFERENCES device (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_history ADD CONSTRAINT FK_2B762919700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_history ADD CONSTRAINT FK_2B762919B03A8386 FOREIGN KEY (created_by_id) REFERENCES technician (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE technician DROP CONSTRAINT FK_F244E9485CB2E05D');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA35CF77DD3');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA394A4C7D4');
        $this->addSql('ALTER TABLE ticket_history DROP CONSTRAINT FK_2B762919700047D2');
        $this->addSql('ALTER TABLE ticket_history DROP CONSTRAINT FK_2B762919B03A8386');
        $this->addSql('DROP TABLE device');
        $this->addSql('DROP TABLE technician');
        $this->addSql('DROP TABLE ticket');
        $this->addSql('DROP TABLE ticket_history');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
